resource "aws_elasticache_replication_group" "tfer--redis-cache" {
  at_rest_encryption_enabled = "true"
  auto_minor_version_upgrade = "false"
  automatic_failover_enabled = "false"
  cluster_mode               = "disabled"
  data_tiering_enabled       = "false"
  description                = "redis-cache "
  engine                     = "redis"
  engine_version             = "7.1"
  ip_discovery               = "ipv4"
  maintenance_window         = "wed:03:00-wed:04:00"
  multi_az_enabled           = "false"
  network_type               = "ipv4"
  node_type                  = "cache.t3.medium"
  num_cache_clusters         = "1"
  num_node_groups            = "1"
  parameter_group_name       = "default.redis7"
  port                       = "6379"
  replicas_per_node_group    = "0"
  replication_group_id       = "redis-cache"
  security_group_ids         = ["sg-03d83455902e78887"] #Replace with the live SG Id
  snapshot_retention_limit   = "1"
  snapshot_window            = "01:30-02:30"
  subnet_group_name          = "${aws_elasticache_subnet_group.tfer--redis-subnet-group.name}"
  transit_encryption_enabled = "false"
}
