name: Terrascan Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the full repo is checked out

      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | jq -r '.assets[] | select(.name | contains("Linux_x86_64")) | .browser_download_url')" -o terrascan
          chmod +x terrascan
          sudo mv terrascan /usr/local/bin/

      - name: Verify Directory Structure (Debugging Step)
        run: ls -R

      - name: Run Terrascan Security Scan
        id: terrascan
        run: terrascan scan -d ./gaming-infra -t aws -o json
