on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the full repo is checked out

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Verify Directory Structure (Debugging Step)
        run: ls -R

      - name: Install jq (Dependency for Fetching Latest Terrascan)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Terrascan (Latest Version)
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | jq -r '.assets[] | select(.name | test("Linux_x86_64.tar.gz$")) | .browser_download_url')" -o terrascan.tar.gz
          tar -xvzf terrascan.tar.gz terrascan
          chmod +x terrascan
          sudo mv terrascan /usr/local/bin/

      - name: Verify Terrascan Installation
        run: terrascan version

      - name: Run Terrascan Security Scan
        id: terrascan
        continue-on-error: true  # Allow pipeline to continue even if violations are found
        run: |
          terrascan scan --iac-type terraform --iac-dir ./gaming-infra --output json | tee terrascan-report.json

      - name: Upload Terrascan Report (Artifacts)
        uses: actions/upload-artifact@v3
        with:
          name: terrascan-report
          path: terrascan-report.json
