name: Checkov Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the full repo is checked out

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Verify Directory Structure (Debugging Step)
        run: ls -R

      - name: Run Checkov Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./Terraform-Full-Infrastructure/gaming-infra # Scan the root directory or specify the correct subdirectory
          framework: terraform
          soft_fail: false  # Set to true if you want to allow failures without breaking the pipeline
          quiet: false  # Set to true for less verbose output