name: Terrascan Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the full repo is checked out

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Verify Directory Structure (Debugging Step)
        run: ls -R

      - name: Install Terrascan
        run: |
          curl -s https://raw.githubusercontent.com/accurics/terrascan/main/scripts/install.sh | bash
          sudo mv terrascan /usr/local/bin

      - name: Run Terrascan Security Scan
        id: terrascan
        run: |
          terrascan scan -t terraform -p ./gaming-infra # Scan the root directory or specify the correct subdirectory
